export type BentoAuthContract = {
  readonly authorization: 'basic';
  readonly userAgentPrefix: 'bento-node-';
};

export type BentoEndpointContract = {
  readonly domain: string;
  readonly operation: string;
  readonly method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly siteUuid: 'query' | 'body';
  readonly auth: BentoAuthContract;
  readonly bodyWrapper?: string;
  readonly queryKeys?: readonly string[];
  readonly successStatuses?: readonly number[];
};

const defaultAuth = {
  authorization: 'basic',
  userAgentPrefix: 'bento-node-',
} as const satisfies BentoAuthContract;

export const bentoEndpointContracts = [
  {
    domain: 'sequences',
    operation: 'listSequences',
    method: 'GET',
    path: '/fetch/sequences',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['page'],
    successStatuses: [200],
  },
  {
    domain: 'sequences',
    operation: 'createSequenceEmail',
    method: 'POST',
    path: '/fetch/sequences/:sequenceId/emails/templates',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'email_template',
    successStatuses: [200, 201],
  },
  {
    domain: 'emailTemplates',
    operation: 'getEmailTemplate',
    method: 'GET',
    path: '/fetch/emails/templates/:id',
    siteUuid: 'query',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'emailTemplates',
    operation: 'updateEmailTemplate',
    method: 'PATCH',
    path: '/fetch/emails/templates/:id',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'email_template',
    successStatuses: [200],
  },
  {
    domain: 'tags',
    operation: 'listTags',
    method: 'GET',
    path: '/fetch/tags',
    siteUuid: 'query',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'tags',
    operation: 'createTag',
    method: 'POST',
    path: '/fetch/tags',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'tag',
    successStatuses: [200, 201],
  },
  {
    domain: 'tags',
    operation: 'deleteTag',
    method: 'DELETE',
    path: '/fetch/tags/:id',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'tag',
    successStatuses: [200],
  },
  {
    domain: 'fields',
    operation: 'listFields',
    method: 'GET',
    path: '/fetch/fields',
    siteUuid: 'query',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'fields',
    operation: 'createField',
    method: 'POST',
    path: '/fetch/fields',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'field',
    successStatuses: [200, 201],
  },
  {
    domain: 'subscribers',
    operation: 'getSubscriber',
    method: 'GET',
    path: '/fetch/subscribers',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['email', 'uuid'],
    successStatuses: [200],
  },
  {
    domain: 'subscribers',
    operation: 'createSubscriber',
    method: 'POST',
    path: '/fetch/subscribers',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'subscriber',
    successStatuses: [200, 201],
  },
  {
    domain: 'segments',
    operation: 'matchSegment',
    method: 'POST',
    path: '/fetch/segments/:id/match',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: undefined,
    successStatuses: [200],
  },
  {
    domain: 'commands',
    operation: 'runCommand',
    method: 'POST',
    path: '/fetch/commands',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'command',
    successStatuses: [200, 201],
  },
  {
    domain: 'batch',
    operation: 'importSubscribers',
    method: 'POST',
    path: '/batch/subscribers',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'subscribers',
    successStatuses: [200, 201],
  },
  {
    domain: 'batch',
    operation: 'importEvents',
    method: 'POST',
    path: '/batch/events',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'events',
    successStatuses: [200, 201],
  },
  {
    domain: 'batch',
    operation: 'sendTransactionalEmails',
    method: 'POST',
    path: '/batch/emails',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'emails',
    successStatuses: [200, 201],
  },
  {
    domain: 'broadcasts',
    operation: 'listBroadcasts',
    method: 'GET',
    path: '/fetch/broadcasts',
    siteUuid: 'query',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'broadcasts',
    operation: 'createBroadcast',
    method: 'POST',
    path: '/batch/broadcasts',
    siteUuid: 'body',
    auth: defaultAuth,
    bodyWrapper: 'broadcasts',
    successStatuses: [200, 201],
  },
  {
    domain: 'stats',
    operation: 'getSiteStats',
    method: 'GET',
    path: '/stats/site',
    siteUuid: 'query',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'stats',
    operation: 'getSegmentStats',
    method: 'GET',
    path: '/stats/segment',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['segment_id'],
    successStatuses: [200],
  },
  {
    domain: 'stats',
    operation: 'getReportStats',
    method: 'GET',
    path: '/stats/report',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['report_id'],
    successStatuses: [200],
  },
  {
    domain: 'stats',
    operation: 'getAdsStats',
    method: 'GET',
    path: '/stats/ads',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['dimension', 'value', 'start_date', 'end_date', 'revenue_mode'],
    successStatuses: [200],
  },
  {
    domain: 'experimental',
    operation: 'validateEmail',
    method: 'POST',
    path: '/experimental/validation',
    siteUuid: 'body',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'experimental',
    operation: 'guessGender',
    method: 'POST',
    path: '/experimental/gender',
    siteUuid: 'body',
    auth: defaultAuth,
    successStatuses: [200],
  },
  {
    domain: 'experimental',
    operation: 'geolocateIp',
    method: 'GET',
    path: '/experimental/geolocation',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['ip'],
    successStatuses: [200],
  },
  {
    domain: 'experimental',
    operation: 'checkBlacklist',
    method: 'GET',
    path: '/experimental/blacklist',
    siteUuid: 'query',
    auth: defaultAuth,
    queryKeys: ['domain', 'ip'],
    successStatuses: [200],
  },
  {
    domain: 'experimental',
    operation: 'getContentModeration',
    method: 'POST',
    path: '/experimental/content_moderation',
    siteUuid: 'body',
    auth: defaultAuth,
    successStatuses: [200],
  },
] as const satisfies readonly BentoEndpointContract[];
